name: Keep GitHub Streak Alive

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Tushar-programador"
          git config user.email "155283301+Tushar-programador@users.noreply.github.com"

      - name: Sync with Main
        run: |
          git pull --rebase origin main

      - name: Update File
        run: |
          echo "Last update: $(date -u)" > streak.txt

      - name: Commit and Push
        run: |
          git add streak.txt

          git commit -m "Daily streak update $(date -u +'%Y-%m-%d')" || exit 0

          git push origin main
